"""The run stops at whichever of NBin or CPU_MAX comes first.

Upstream ALF discards NBin whenever CPU_MAX is set, so a run always burns its
whole time budget. This fork gates that override on NBin being unset, which is
what lets a checkpoint-restart driver ask for an exact number of bins and still
stay inside its wall-clock allocation.

Needs a built binary, so it skips unless ``Prog/ALF.out`` exists:

    cd ALF && source configure.sh GNU noMPI HDF5 && make program
    pytest testsuite/test_nbin_cpu_max.py
"""

import os
import subprocess
from pathlib import Path

import pytest

h5py = pytest.importorskip("h5py")
py_alf = pytest.importorskip("py_alf")

ALF_DIR = Path(__file__).resolve().parent.parent
ALF_BIN = ALF_DIR / "Prog" / "ALF.out"

pytestmark = pytest.mark.skipif(
    not ALF_BIN.exists(), reason=f"{ALF_BIN} not built; run `make program` first"
)

# Small enough that a bin costs a few milliseconds, so a bin-bounded run
# finishes quickly and a time-bounded one still produces plenty of bins.
BASE_PARAMS = {
    "Model": "Hubbard_Plain_Vanilla",
    "Lattice_type": "Square",
    "L1": 4,
    "L2": 4,
    "Ham_T": 1.0,
    "Ham_U": -4.0,
    "Ham_chem": 0.0,
    "Beta": 1.0,
    "Dtau": 0.1,
    "Projector": False,
    "Symm": True,
    "Nwrap": 5,
    "Nsweep": 20,
    "Ltau": 0,
}


def _run_alf(tmp_path, nbin, cpu_max):
    """Run ALF once in *tmp_path* and return the bins it wrote.

    The parameters file is generated by py_alf rather than hand-written, so
    every namelist ALF expects is present -- the same approach test_vs_ed uses.
    """
    sim = py_alf.Simulation(
        py_alf.ALF_source(str(ALF_DIR)),
        "Hubbard_Plain_Vanilla",
        {**BASE_PARAMS, "NBin": nbin, "CPU_MAX": cpu_max},
        sim_root=str(tmp_path),
        sim_dir=".",
        mc_seed=13579,
        hdf5=True,
    )
    sim.run(only_prep=True)

    env = os.environ.copy()
    env["OMP_NUM_THREADS"] = "1"
    subprocess.run([str(ALF_BIN)], cwd=sim.sim_dir, env=env, check=True, timeout=600)

    with h5py.File(Path(sim.sim_dir) / "data.h5", "r") as f:
        return int(f["Ener_scal/obser"].shape[0])


def test_bin_bound_wins_when_it_is_reached_first(tmp_path):
    """A reachable NBin must be honoured exactly, not overshot.

    The time budget here is far larger than the work, so without the fix ALF
    would run the full CPU_MAX and produce many more bins than asked for.
    """
    assert _run_alf(tmp_path, nbin=20, cpu_max=1.0) == 20


def test_time_bound_still_applies_when_bins_are_out_of_reach(tmp_path):
    """A tiny budget must still truncate cleanly, well short of NBin.

    This is the graceful-stop path a checkpoint restart depends on: ALF breaks
    the bin loop on time, having already flushed the bins it completed.
    """
    bins = _run_alf(tmp_path, nbin=1_000_000, cpu_max=0.003)
    assert 0 < bins < 1_000_000


def test_no_bin_bound_is_pure_time_bounding(tmp_path):
    """NBin <= 0 keeps upstream's behaviour: run for the whole budget."""
    bins = _run_alf(tmp_path, nbin=0, cpu_max=0.003)
    assert bins > 0


def test_bins_accumulate_across_a_restart(tmp_path):
    """Resuming appends to data.h5, so the bin bound counts this run's bins.

    That is what makes ``NBin = target - bins_on_disk`` land exactly on target.
    """
    first = _run_alf(tmp_path, nbin=10, cpu_max=1.0)
    assert first == 10

    # py_alf's prep promotes confout_* -> confin_* on the next run, which is
    # what makes this a resume rather than a fresh start.
    assert _run_alf(tmp_path, nbin=5, cpu_max=1.0) == 15
